#!/bin/bash
#Script de Backup das configuracoes dos switches das UPAs
cd /backup_sw
#dt=$(date '+%d%m%Y');
dt=$(date '+%Y%m%d');
echo Starting Backup...Wait...
cat /backup_sw/ips_list_upa.txt |  while read output
do
expect sw_get_backup_upa $output | tee -a /backup_sw/results/$dt"_"$1"_upa".txt
	clear
	echo Starting Next Host...Wait... 
done
tar -cvf sw_$dt"_upa".tar /tftp/upa_sw*.cfg
rm -rf /tftp/upa_sw*.cfg
mv -f /backup_sw/sw_$dt"_upa".tar /backup_sw/data
 

