#!/bin/bash
#Script de Backup das configuracoes dos switches do IHB
cd /backup_sw
#dt=$(date '+%d%m%Y');
dt=$(date '+%Y%m%d');
echo Starting Backup...Wait...
cat /backup_sw/ips_list_dell.txt |  while read output
do
expect sw_get_backup_dell $output | tee -a /backup_sw/results/$dt"_"$1.txt
	clear
	echo Starting Next Host...Wait... 
done
tar -cvf sw_dell_$dt.tar /tftp/sw*.conf
rm -rf /tftp/sw*.conf
mv -f /backup_sw/sw_dell_$dt.tar /backup_sw/data
 

